// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgMeta.Data;

#nullable disable

namespace MtgMeta.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221205143936_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CartaMazzo", b =>
                {
                    b.Property<int>("carteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mazziMazzoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("carteId", "mazziMazzoId");

                    b.HasIndex("mazziMazzoId");

                    b.ToTable("CartaMazzo");
                });

            modelBuilder.Entity("MtgMeta.Models.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prezzo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Carte");
                });

            modelBuilder.Entity("MtgMeta.Models.Mazzo", b =>
                {
                    b.Property<int>("MazzoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentualeMeta")
                        .HasColumnType("INTEGER");

                    b.HasKey("MazzoId");

                    b.ToTable("Mazzi");
                });

            modelBuilder.Entity("CartaMazzo", b =>
                {
                    b.HasOne("MtgMeta.Models.Carta", null)
                        .WithMany()
                        .HasForeignKey("carteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMeta.Models.Mazzo", null)
                        .WithMany()
                        .HasForeignKey("mazziMazzoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
