// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgMeta.Data;

#nullable disable

namespace MtgMeta.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221129100759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("MtgMeta.Models.Mazzo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PercentualeMeta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lista")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mazzi");
                });
#pragma warning restore 612, 618
        }
    }
}
